### ISSUE TITLE
Multispecies fitting

### ISSUE THREAD

**Issue by casv2** [JuliaMolSim/SHIPs.jl#6] opened 2020-06-17 15:17 UTC
Doing a multi species fit generally results in a large condition number R (e.g. 1e164) for which doing a regular QR decomposition results in a LAPACK error. Performing the fit with RRQR does work.

**Comment by gabor1** [comment] 2020-06-17 15:20
Rather than just powering through it, is it reasonable to see these huge condition numbers? is there not a bug? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by cortner** [comment] 2020-06-17 18:18
That’s why I asked Cas to open an issue

**Comment by cortner** [comment] 2020-06-29 22:43
@casv2 Does the workaround take care of the condition number issues as well?

**Comment by cortner** [comment] 2020-06-29 22:44
We won't close this issue yet though until I've fixed the bug properly.

**Comment by casv2** [comment] 2020-06-29 22:45
Yes condition number seems fine right now!

**Comment by cortner** [comment] 2020-06-30 18:08
since the new workaround should not affect performance anymore and since Cas' latest tests seem to confirm this is now all resolved, I'll close this (moving the remaining puzzle to #7)  .  (fixed as of JuLIP v0.9.6 and SHIPs v0.6.6 )

@casv2 Please feel free to reopen if another issue arises.

**Closed** 2020-06-30 18:08 UTC
